//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveEmpSkill
    {
        public int Id { get; set; }
        public Nullable<int> EmpskillAdd_Id { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public string TaskAssigned { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsEvaluated { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual EmployeeSkillsAdd EmployeeSkillsAdd { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
