//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignEvaluater
    {
        public int Id { get; set; }
        public Nullable<int> AssignResource_Id { get; set; }
        public Nullable<long> Trainer_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Trainer Trainer { get; set; }
        public virtual AssignResource AssignResource { get; set; }
    }
}
