//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriticalResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CriticalResource()
        {
            this.criticalResourceAccountabilities = new HashSet<criticalResourceAccountability>();
            this.Trainers = new HashSet<Trainer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PersonalInfo_Id { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsNotified { get; set; }
    
        public virtual ProjectsDetail ProjectsDetail { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<criticalResourceAccountability> criticalResourceAccountabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainer> Trainers { get; set; }
    }
}
