//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentInfo
    {
        public int Id { get; set; }
        public Nullable<int> P_Id { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DateOfRelieving { get; set; }
        public string ReportingManager { get; set; }
        public string JobType { get; set; }
        public string DeployedCompanyDetails { get; set; }
        public Nullable<System.DateTime> DeployedFromDate { get; set; }
        public Nullable<System.DateTime> DeployedToDate { get; set; }
        public string CompanyMailId { get; set; }
        public string BankName { get; set; }
        public string IFSC { get; set; }
        public string ModeOfPayment { get; set; }
        public string WorkLocation { get; set; }
        public string Department { get; set; }
        public string Grade { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> CTC { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
