//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationQualification
    {
        public int Id { get; set; }
        public Nullable<int> P_Id { get; set; }
        public string Degree { get; set; }
        public string Board { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
