//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEvalTaskDet
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeEvalTask_Id { get; set; }
        public Nullable<long> Employee_Id { get; set; }
        public string TaskAssigned { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsEligiableMark { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual EmployeeEvalTask EmployeeEvalTask { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
