//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleDet
    {
        public int Id { get; set; }
        public Nullable<int> Module_Id { get; set; }
        public string Topics { get; set; }
        public Nullable<System.TimeSpan> HoursRequired { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
