//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleDet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleDet()
        {
            this.TrainingDets = new HashSet<TrainingDet>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Module_Id { get; set; }
        public string Topics { get; set; }
        public Nullable<System.TimeSpan> HoursRequired { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingDet> TrainingDets { get; set; }
    }
}
