//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public Nullable<long> User_Id { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsNotified { get; set; }
        public Nullable<int> Sessions_Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
