//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsWorked
    {
        public int Id { get; set; }
        public Nullable<int> P_Id { get; set; }
        public string ProjectName { get; set; }
        public string Designation { get; set; }
        public string Responsibilities { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> TeamMembers { get; set; }
        public Nullable<int> Manager_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual PersonalInfo PersonalInfo { get; set; }
    }
}
