//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectsWorked
    {
        public int Id { get; set; }
        public Nullable<int> PersonalInfo_Id { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public string Designation { get; set; }
        public string Responsibilities { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> TeamMembers { get; set; }
        public Nullable<long> Manager_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual PersonalInfo PersonalInfo { get; set; }
        public virtual ProjectsDetail ProjectsDetail { get; set; }
        public virtual ProjectsWorked ProjectsWorked1 { get; set; }
        public virtual ProjectsWorked ProjectsWorked2 { get; set; }
        public virtual ProjectsWorked ProjectsWorked11 { get; set; }
        public virtual ProjectsWorked ProjectsWorked3 { get; set; }
    }
}
