//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetentionTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingDet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingDet()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Training_Id { get; set; }
        public Nullable<int> ModuleDet_Id { get; set; }
        public Nullable<System.TimeSpan> HoursRequired { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual Training Training { get; set; }
        public virtual ModuleDet ModuleDet { get; set; }
    }
}
